### ISSUE TITLE
circular reference warning with ruby 2.2

### ISSUE THREAD

**Issue by gingerlime** [plataformatec/simple_form#1184]
`/usr/lib/ruby/gems/2.2.0/gems/simple_form-3.0.2/lib/simple_form/inputs/boolean_input.rb:38: warning: circular argument reference - unchecked_value`

**Comment by gingerlime** [comment]
seems to have been updated since `3.0.2`... False alarm.

**Comment by subelsky** [comment]
I'm still getting this on `3.0.3`, ruby 2.2.2 and rails 4.1.10

**Comment by carlosantoniodasilva** [comment]
@subelsky it seems to be [fixed on the v3.0 branch](https://github.com/plataformatec/simple_form/tree/v3.0) only, try that.

**Comment by samjohn** [comment]
What version of simple form should I install to fix this? Is it released?

Thanks!

**Comment by carlosantoniodasilva** [comment]
@samjohn it hasn't been released, you must bundle from v3.0 branch to get this fix.

**Comment by samjohn** [comment]
ah, thanks. Is there an expected release date?

**Comment by carlosantoniodasilva** [comment]
Technically v3.0 is closed since we released v3.1, so there shouldn't be new releases, except if we find some security issue, but I think we can cut a new v3.0.4 version with this fix since many people are hitting it.

If you can, I'd recommend migrating to v3.1.0, though, there are [plenty of improvements/fixes on this version](https://github.com/plataformatec/simple_form/blob/master/CHANGELOG.md#310) :)

**Comment by jfeust** [comment]
@carlosantoniodasilva Any word on that 3.0.4 release?

**Comment by carlosantoniodasilva** [comment]
@jfeust released! 26edeca5fa829d1d62d666895406e6943425b91f, hope that helps :)
