### ISSUE TITLE
3.1.0 breaks item_wrapper_class

### ISSUE THREAD

**Issue by hackeron** [plataformatec/simple_form#1195]
Before updating to 3.1, I could use item_wrapper_class to change the label class like so:

```ruby
= f.input_field :time_of_day,
     collection: [:all, :morning, :afternoon, :evening, :night],
     checked: params[:events][:time_of_day],
     as: :radio_buttons, item_wrapper_class: 'button secondary small'
```

To generate this:

```html
<label class="radio button secondary small">
  <input class="radio_buttons required" id="events_time_of_day_business_hours" name="events[time_of_day]" type="radio" value="business_hours"> Business Hours
</label>
```

Now with 3.1 the same code generates:

```html
<span class="radio button secondary small">
  <label for="events_time_of_day_business_hours">
    <input item_wrapper_class="button secondary small" class="radio_buttons required" type="radio" value="business_hours" name="events[time_of_day]" id="events_time_of_day_business_hours"> Business Hours
  </label>
</span>
```

How do I the old expected behaviour back?

**Comment by davidlfox** [comment]
Wasn't aware of the previous behavior, but I'm trying to figure out how to omit `<label for...>` when using .input. Attempting to generate Bootstrap toggle radio buttons using `.input` e.g. 

    = f.input :the_field,
        :label => false,
        :collection => [ ['val1', 'text1'],['val2', 'text2'] ],
        :as => :radio_buttons,
        :label_method => :last,
        :value_method => :first,
        :checked => @chore.direction,
        :input_html => { :class => 'a-class' },
        :item_wrapper_tag => :label,
        :item_wrapper_class => 'btn btn-primary',
        :collection_wrapper_tag => :div,
        :collection_wrapper_class => 'btn-group'

generates `item_wrapper_tag` correctly, but injects `<label for...>` immediately inside that and impacts the Bootstrap styles.

**Comment by carlosantoniodasilva** [comment]
That was a necessary change, previously the label was considered the "wrapper tag" but that was wrong, Simple Form now generates a real "wrapper tag": a `span`. The label + input output can be tweaked in some ways, explained bellow.

You can generate the items as you want by passing a block to the f.input call, when using radio/checkbox collections. It will yield a builder so that you can tweak how to generate input and label the way you need. [Here's an example](https://github.com/plataformatec/simple_form/blob/v3.1.0/lib/simple_form/form_builder.rb#L339).

You may also try to tweak the [`boolean_style` flag](https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L57).

I hope that helps, I'm giving this a close for now, please let us know if you still find this is an issue and we can reopen. Thanks.

**Comment by jmmcduffie** [comment]
I'm seeing a slightly different issue with `item_wrapper_class` on 3.1.0. It works if I pass it in when calling `f.input :foo, item_wrapper_class: "bar"` but not if I set the `config.item_wrapper_class = "bar"` option in the simple_form initializer.

**Comment by hackeron** [comment]
I managed to resolve this problem by renaming item_wrapper_class to item_label_class - thank you :)
