### ISSUE TITLE
Nested Resources + Naming Routes

### ISSUE THREAD

**Issue by bglbruno** [plataformatec/simple_form#1205]
Hi, in my app I have the following code:

in `_form.html.slim`
```ruby
 = simple_form_for([@dynamic_management, @dynamic_management_item]) do |f|
   # form inputs
```
and in `routes.rb`
```ruby
resources :dynamic_managements, path: :dm, as: :dm, only: [:index] do
   resources :dynamic_management_items, path: :item, as: :item
end
```

But, it doesn't work with simple_form. It expect a method called `dynamic_management_dynamic_management_item_path`, but the correct is `dm_item_path`.

I don't know if it is a bug or not.
What's the solution for that?

**Comment by carlosantoniodasilva** [comment]
This is a functionality provided by Rails called polymorphic routes: it "tries" to figure out the correct route name based on your object. Since you've changed the routes naming, it's not gonna work, so you need to provide the `url` option yourself.

Please use the mailing list or stack overflow for questions, we reserve the issues tracker for issues. Thanks!

**Comment by bglbruno** [comment]
Ok @carlosantoniodasilva, sorry about that, thank for helping.

**Comment by carlosantoniodasilva** [comment]
No problem :), glad to help.

On Wed, Feb 11, 2015 at 5:30 PM, Bruno Gonçales <notifications@github.com>
wrote:

> Ok @carlosantoniodasilva <https://github.com/carlosantoniodasilva>, sorry
> about that, thank for helping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/simple_form/issues/1205#issuecomment-73947421>
> .
>



-- 
At.
Carlos Antonio
