### ISSUE TITLE
"Localized options" does not fallback to default i18n fallback

### ISSUE THREAD

**Issue by nicolasblanco** [plataformatec/simple_form#1228]
Hi,

I've noticed that simple_form does not fallback to the default fallback locale if the localized options object don't exist in the main locale.

For example if an option field is `doctor.title`, and locale is 'fr-MA' with fallback to 'fr' (`config.i18n.fallbacks = { 'fr-MA' => 'fr' }`), it will only look on `fr-MA.simple_form.options.doctor.title` but does not fallback to `fr.simple_form.options.doctor.title`.

This behavior is not expected as the default fallbacks work perfectly for labels for instance...

Thanks.

**Comment by carlosantoniodasilva** [comment]
Hi @nicolasblanco, that happens because Simple Form does not translate every option separately, [it just grabs the entire options hash](https://github.com/plataformatec/simple_form/blob/v3.1.0/lib/simple_form/inputs/collection_input.rb#L99) and processes it. If you don't have the options set on the main locale, the fallback mechanism from I18n should work fine I think, however if you do, then Simple Form will just use the first options it finds.

Unfortunately I think doing that for every option would be super expensive perf-wise, for example #1227 seems to be a case where I18n can cause slow down, so I believe Simple Form shouldn't try to localize every option.

Does that answer your question?

Thanks!
