### ISSUE TITLE
if i use custom wrapper, how to set default form class?

### ISSUE THREAD

**Issue by hiphapis** [plataformatec/simple_form#1231]
if set custom wrapper && set default form class in custom wrapper
then form class are set default form class in custom wrapper

Current version
`_form.html.erb`
```ruby
<%= simple_form_for SOMEPATH, html: { class: "form-horizontal" }, wrapper: :horizontal do |f| %>
```
then rendered
```html
<form class="simple_form form-horizontal">
```
currently manual set form class.
how about this?
`_form.html.erb`
```ruby
<%= simple_form_for SOMEPATH, wrapper: :horizontal do |f| %>
```
`simple_form configure file`
```ruby
config.wrappers :horizontal, class: "form-group" do |b|
  b.default_form_class "form-horizontal"
end
```
then rendered
```html
<form class="simple_form form-horizontal">
```

i look for this feature, but i could not found it.

**Comment by carlosantoniodasilva** [comment]
Unfortunately the form class can only be set globally, not per-wrapper, and that's because wrappers are associated with each input, not with the form itself (the ability to set a wrapper for the entire form is an addition to avoid having to pass it for each input).

You have the global `form_class` and `default_form_class` options to set on your Simple Form initializer, they apply to all forms. If you want a custom class to be passed to specific forms, you could come up with a helper of your own, like this:

```ruby
def horizontal_simple_form_for(path, options = {}, &block)
  options = options.deep_merge(html: { class: 'form-horizontal' }, wrapper: :horizontal)
  simple_form_for(path, options, &block)
end
```

(totally untested).

**Comment by hiphapis** [comment]
aha! i got it.
Thanks @carlosantoniodasilva ;)

**Comment by lukasedw** [comment]
In ruby-version is set 2.4.1, then i set in travis ruby ​​2.4.1 either.
