### ISSUE TITLE
Bootstrap form-horizontal not working

### ISSUE THREAD

**Issue by cbetta** [plataformatec/simple_form#1233]
I just build a fresh Rails 4.2.1 app with the following gems:

```ruby
gem 'simple_form'
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
end
```

But whatever I do I can't get the horizontal form to look right. My form looks like this:

```erb
  <%= simple_form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
    <%= f.input :id %>
    <%= f.input :name %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
```

And obviously added boostrap to my `application.scss`:

```scss
/*
 *= require_tree .
 *= require bootstrap
 *= require_self
 */
```

Regardless my horizontal form doesnt work:

![screen shot 2015-03-28 at 14 44 35](https://cloud.githubusercontent.com/assets/7718/6881080/fad817e2-d558-11e4-85ac-0ec7168dfa29.png)

What am I doing wrong? Google is full of search results regarding the BS2->3 transition which didnt help me.

**Comment by cbetta** [comment]
FWIW, `simple_form` was locked at `3.1.0` and  `bootstrap` at `3.3.4`

**Comment by cbetta** [comment]
I've pushed my code to https://github.com/cbetta/simple-form-bootstrap-test if someone wants to play with it

**Comment by carlosantoniodasilva** [comment]
There's an [example of horizontal form on our bootstrap playground/test app](https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/app/views/examples/_horizontal_form_sf.html.erb), have you tried it? Make sure to check the initializer config file to see if you spot any differences from yours.

I'm giving this a close, since it doesn't seem to actually be a bug, I'd recommend you to try the mailing list to seek for more help, and in case it turns out to be a real Simple Form bug we can always reopen :). Thanks!

**Comment by cbetta** [comment]
Maybe not a bug but definitely an omission in the docs regarding the necessity to add the wrapper and wrapper_mappings to the form. Anyway, tnx @carlosantoniodasilva my problem has been resolved with that.

**Comment by carlosantoniodasilva** [comment]
Great that it was resolved, and sorry about the docs, Simple Form does not mean to include documentation on every single possible integration with bootstrap (or other css frameworks), the only goal is to make it possible for users to configure it to achieve what they need :). We created that playground app hoping that could be the best way to do that with bootstrap. Anyway, thanks <3

**Comment by cbetta** [comment]
Sure but the initialization of `simple_form_bootstrap.rb` does suggest it takes care of the horizontal form. Thanks again

**Comment by carlosantoniodasilva** [comment]
The problem might be that for a particular wrapper, there is no way to set a different wrapper mapping for different inputs from the configuration, which is why we need to do that on the form (meaning we set the horizontal wrapper AND each specific input mapping as well).

@cbetta @rafaelfranca do you guys think that makes sense?

**Comment by cbetta** [comment]
Totally makes sense.
