### ISSUE TITLE
Span after checkbox

### ISSUE THREAD

**Issue by Svashta** [plataformatec/simple_form#1234]
Hi,

i've already asked this on stackoverflow but no useful replies have been made so far, so i hope it is ok to ask here, too.

I am getting a span element in the html when using:
`f.input :attribute, :as => :boolean`

Not only one, but two. One after hidden element, one after visible one.
So the final output is something like this:

---
    <input value="0" type="hidden" name="model[attribute]">
    <span></span>
    <label class="boolean optional" for="model_attribute">
      <input class="boolean optional" type="checkbox" value="1" name="model[attribute]" id="model_attribute">
      <span></span>Label Text
    </label>
---

The first span is totally unnecessary, or at least i don't see why it should be there.
The second one, at least for me, is not necessary

How can I get rid of span element?

**Comment by carlosantoniodasilva** [comment]
I see you already tried on stack overflow, but please try the mailing list for questions, we reserve the issues tracker for issues.

Also I'd recommend adding as much information as possible, like the simple form wrapper config you're using on this form/input, if you have any custom boolean input for example, which simple form version you're using, or even an example app to reproduce the problem, so that people can more easily help you. If that turns out to be a real bug I'd be more than happy to reopen here.

Thanks!
