### ISSUE TITLE
input wrapper decision order should prefer form-specific wrapper over mappings

### ISSUE THREAD

**Issue by lowjoel** [plataformatec/simple_form#1258]
Currently, the wrapper for a field is defined as:

 1. The specific type of wrapper specified on the input call
 2. The default wrapper mapping
 3. The current form's wrapper

It feels counterintuitive that the current form's wrapper takes lower precedence than the defaults configured in the initialiser.

If this is indeed believed to be a bug I should be able to file a PR to solve it.

**Comment by carlosantoniodasilva** [comment]
Right, the issue is that the form given wrapper is global for all inputs, whereas the input mapping can be added per-form or through the config. That gives you a hook to change a specific input mapping, so basically what Simple Form does is:

1. Look for specific input mapping
  1. the input `:wrapper` option
  2. the form `:wrapper_mappings` option
  3. the config `:wrapper_mappings` option
2. Look for global form mapping
  1. the form `:wrapper` option
  2. the config `:default_wrapper`

Looking at this again, it seems the current lookup makes sense. I'm not sure changing the lookup to move the config `wrapper_mappings` to after the form `wrapper` would be the best thing to do.

Thoughts? Thanks!

**Comment by lowjoel** [comment]
My take is that the config wrapper mappings should come after the form wrapper because then the whole wrapper decision process would be 'lexically scoped', if we treated Simple Form as a DSL.

The current behaviour would make sense only if one knew how Simple Form was implemented, which might be counter to the whole reason for a DSL in the first place.

**Comment by carlosantoniodasilva** [comment]
If we do that, and for example you want to override the input mapping for countries to be a string input instead of the country select plugin like we show in the readme:

```ruby
config.input_mappings = { /country/ => :string }
```

Every time you use a different wrapper in a form, you'd have to also specify a mapping for the country fields in case you have them in that same form, because now we'd be defaulting to the form's wrapper first, and the input mappings afterwards. This would lead to duplicated form wrapper + mappings definitions in your application.

I still think it's more sane to check input mappings first, form wrappers second, but I'm open to see what others think so we can reach a conclusion that's better for Simple Form in the long run.

@rafaelfranca @josevalim @lucasmazza any thoughts on this one?

**Comment by rafaelfranca** [comment]
I have to agree with @carlosantoniodasilva on this one. The wrapper mappings should take precedence over the form wrapper in all cases. We should see the form wrapper as a default in case any wrapper can be found using the mapping.

**Comment by asiniy** [comment]
Is there any progress related to this?
