### ISSUE TITLE
textarea is filled with mysterious white spaces

### ISSUE THREAD

**Issue by piya23300** [plataformatec/simple_form#1268]
I use textarea for nested field.
I don't know why textarea is filled with mysterious white spaces.

my code
```
= f.simple_fields_for :steps do |step_form|
        = step_form.input :description, as: :text, label: false, input_html: { class: 'nested_field' }
```

result
```
<textarea class="text optional nested_field" placeholder="how to ..." name="recipe[steps_attributes][1434631626139][description]" id="recipe_steps_attributes_1434631626139_description">        </textarea>
```

Help me, please....

**Comment by carlosantoniodasilva** [comment]
Please use the mailing list or stack overflow for questions, we reserve the issues tracker for issues. Thanks!

**Comment by blimey85** [comment]
This is a bug. I'm experiencing the same thing. I have a placeholder value set and it doesn't show because there are spaces being inserted. Rather than simple_form generating <textarea></textarea> it's generating <textarea>     </textarea>. When I then click in the field, the cursor is at the end of these spaces so the user has to first delete them, and then can type. I tried setting a default value to an empty string but that didn't solve it.

**Comment by pzin** [comment]
It's not a simple_form bug. It's happening to me as I use cocoon gem to include nested models in my form. It's (I think) because cocoon grabs HTML code from a data attribute and there are white spaces in it. You can fix this by using an ugly output for your slim, haml, or whatever preprocessor. Anyway, it's happening to me just in development environment, it still works nice in production as there's always the ugly mode on.

**Comment by carlosalbertocruz** [comment]
user google.translate
provavelmente você esta usando assim:
<textarea ...>
<?php echo $foo;?>
</textarea> ...

o correto seria usar tudo em uma linha só, assim:

<textarea ...><?php echo $foo;?></textarea>


até mais. bye

**Comment by endersonmenezes** [comment]
Define your <textarea> and your close tag </ textarea> in same line.
Thx @carlosalbertocruz

**Comment by cassej** [comment]
> Define your <textarea> and your close tag </ textarea> in same line.
> Thx @carlosalbertocruz

it`s not the decision, i have the same problem, when i multistring text inside textarea, like this:
<textarea name="text" class="uk-textarea">{{text}}</textarea>

i have first line on right place, and all other lines have huge number of whitespaces before text
