### ISSUE TITLE
Column Data type text not rendering textarea as default

### ISSUE THREAD

**Issue by trd-jameshwart** [plataformatec/simple_form#1287]
I have read README.md that Simple Form will look at the column type in the database and use an appropriate input for the column.  For example, a column created with type :text in the database will use a textarea input by default.

![text](https://cloud.githubusercontent.com/assets/10732118/8819214/abaf53d6-307c-11e5-8447-c281ba5faac0.png)

so i make this
<%= f.input :other_info, input_html: {class: 'form-control margin-bottom-20'}  %>
and i was expecting a textarea but instead input type text is the output

**Comment by carlosantoniodasilva** [comment]
Yes, it should be a textarea for `:text`, unless it's custom mapped to something else in your config or the ORM is bringing it as `:string` instead, which would render `input type=text`.

You'll need to provide us with more information or a way to reproduce the issue, though (like an example app), otherwise I can't think of anything that could be triggering your issue.

Thanks!
