### ISSUE TITLE
Block, Element, Modifier methodology

### ISSUE THREAD

**Issue by regedarek** [plataformatec/simple_form#1296]
Hi,
Is there already a BEM version of simple_form ? https://css-tricks.com/bem-101/
I other case there is a chance of writing our own wrappers.

**Comment by carlosantoniodasilva** [comment]
Yeah, writing your own wrappers is the way to go, we don't plan on supporting lots of different versions within Simple Form (supporting bootstrap the way it is was already very complicated/problematic, that's why wrappers can be fully customized).

Please feel free to post your findings or an example in the wiki to help others, it'd be appreciated. Thanks!

**Comment by KlonD90** [comment]
@regedarek if you did write somehing can you share it?

**Comment by regedarek** [comment]
I have this on my list for fun friday coding which will be in next week.
