### ISSUE TITLE
Password field is getting field_with_errors class before submitting

### ISSUE THREAD

**Issue by dishark** [plataformatec/simple_form#1300]
My form renders like this

![image](https://cloud.githubusercontent.com/assets/911094/9562212/2475bbc0-4e3c-11e5-8db8-c1914ce5763c.png)

__Note:__ The "não pode ficar em branco" message shouldn't have being displayed.

Code:

````YAML
fieldset
    p If this is your first time here, please register
      = simple_form_for @user do |f|
      = f.input :name, :placeholder => "Enter your name"
      = f.input :email, :placeholder => "Enter your E-mail"
      = f.input :password, :placeholder => "Enter your password"
      = f.input :password_confirmation, :placeholder => "Confirm your password"
      = f.submit "Register"
````

**Comment by josevalim** [comment]
If that is happening is because you are calling something like `valid?` when showing the form for the first time or something similar. simple_form_for just renders the form, if there is an error in your model before that, it is not simple form's fault.

If you still think this is a bug,  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
