### ISSUE TITLE
Rails 4 Association not working

### ISSUE THREAD

**Issue by ishouvik** [plataformatec/simple_form#1303]
I am having a tough time configuring associations on my form.

```ruby
# app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  has_and_belongs_to_many :categories, class_name: ProductCategory, join_table: :products_categories_join
end

# app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_and_belongs_to_many :products, join_table: :products_categories_join
end

# app/models/user.rb
class User < ActiveRecord::Base
  has_many :products, dependent: :destroy
end

#app/views/products/new.html.erb
<%= simple_form_for :user_product, url: user_products_path(@username, @product), html: { role: :form } do |f| %>
 <%= render 'form', f: f %>
<% end %>

# app/views/products/_form.rb
<%= f.association :user %>
<%= f.association :categories %>
```

The error message is:
> Association cannot be used in forms not associated with an object.

The association works on rails console and the view file displays the associated entries.

**Comment by ishouvik** [comment]
Upon further testing it seems that if the `<form>` tag is generated with a non-default Rails method the association input method doesn't work.

The association works if we use 
`<%= simple_form_for(@myvar) %>`

**Comment by carlosantoniodasilva** [comment]
You need to pass an object to the form, not a symbol, otherwise Rails will try to find a variable with that symbol and if it does not, there will be no object associated with the form, thus the associations can't be guessed properly by Simple Form.

Try something like this:

```ruby
simple_form_for @product, url: user_products_path(@username, @product)....
```

Please use the mailing list or stack overflow for questions, we reserve the issues tracker for issues. Thanks!
