### ISSUE TITLE
select for association adds an extra empty value

### ISSUE THREAD

**Issue by lessless** [plataformatec/simple_form#1326]
Hello,

there is a select box for the HABTM association in the view

```
.medium-6.columns
      legend Lieft Team
      = f.simple_fields_for :teams, Team.new  do |tf|
        =tf.association :players, include_blank: false, collection: Player.all
.medium-6.columns
      legend Right Team
      = f.simple_fields_for :teams, Team.new  do |tf|
        =tf.association :players, include_blank: false, collection: Player.all
```

and no matter how many items  are selected there is an extra empty id  in the params:

```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"hg6+cwJHlIxFHap7ZZf0VDJ/vH2FJfErAc3WvHCjo67j2bziYr6n3nWh3HOlRk+fhkEWHVgFC3hQPF8QMKGRdA==", "match"=>{"teams_attributes"=>{"0"=>{"player_ids"=>[""]}, "1"=>{"player_ids"=>["", "3"]}}}, "commit"=>"Create Match"}
```

**Comment by dahal** [comment]
+1

**Comment by teoulas** [comment]
This is on purpose. If there was no hidden empty value and you selected none of the options, your association would not be updated. This is because the player_ids keys would be missing. The empty value is there to ensure the player_ids will be sent to the server on form submission. The use case it covers is when you edit a record and want to remove all associated records.

**Comment by feliperenan** [comment]
Now we have an issue template that helps you provide more information about the issue. Please open a new issue and make sure to fill in all the information requested by the template shown inside the text box. Thank you!
