### ISSUE TITLE
Bootstrap 4 custom forms

### ISSUE THREAD

**Issue by camilleroux** [plataformatec/simple_form#1401]
Bootstrap 4 introduces [custom forms](http://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios-1) to customize checkboxes and radio buttons. Here is a way to generate the following templates? 

````html
<label class="c-input c-checkbox">
  <input type="checkbox">
  <span class="c-indicator"></span>
  Check this custom checkbox
</label>
````

````html
<label class="c-input c-radio">
  <input id="radio1" name="radio" type="radio">
  <span class="c-indicator"></span>
  Toggle this custom radio
</label>
<label class="c-input c-radio">
  <input id="radio2" name="radio" type="radio">
  <span class="c-indicator"></span>
  Or toggle this other custom radio
</label>
````

Thank you!

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
Right now no one trying to make simple form work with bootstrap 4 so we don't have an answer for this question. Unfortunately I don't use simple form anymore but for me it is still fine to maintain the HTML generation since it is the same as the Rails form builders but the bootstrap support will be really hard to me to maintain it since I don't use bootstrap.
