### ISSUE TITLE
Painful upgrade 3.1.0 -> 3.4.0

### ISSUE THREAD

**Issue by benoittgt** [plataformatec/simple_form#1478]
Hello

I have an old app that was using simple_form 3.1.0. We recently updated our app to ruby 2.4.1 and last Rails 4.
I thought it will be a good idea to update at the same time simple_form... What a bad idea...

I did a `bundle update simple_form` then..

1) Fields for my login (user and email) started asking for a minimum of 255 chars without knowing why.. It appears that when you upgrade you have to update the initializer too. I finally added [two lines to disable](https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form.rb#L30-L35) this behavior.
2) Test like `assert page.find_field('E-mail', disabled: true)` start failing... I had to change them to `assert page.find_field('user_email', disabled: true)`. 
3) Fields start to be marked as required by default. Tests that were testing models' validations (with flash notice) start failling.
<img width="385" alt="capture d ecran 2017-03-31 a 16 09 24" src="https://cloud.githubusercontent.com/assets/8417720/24556412/88085384-1634-11e7-82a1-e903d887a780.png">
4) We loose fields labels on few pages

... then I reverted to 3.1.0.. scared to have more surprises

This is sad we don't have any more warnings or notices in [Changelog](https://github.com/plataformatec/simple_form/blob/master/CHANGELOG.md) saying they are breaking changes, text to add to initializer, etc. I love using simple form but I can't deal with so many unwanted surprises.

Do you think it will be possible to  : 
- Add more infos when their is text to add to initializer
- When their new default behavior implemented
- Link any changelog entry to the PR when it's possible

Thanks a lot for the job done on this gem.

**Comment by rafaelfranca** [comment]
Thank you for the report. We should not have any breaking changes on those releases and if we have we consider it a bug.

I just checked the diff between those two versions and something is odd here.

1) The `:minlength` is disabled by default https://github.com/plataformatec/simple_form/compare/v3.1.0...v3.4.0#diff-2a863c44f5077f0154fd9ffcb84a1f13R54, unless your wrapper enabled it, or you don't have a default wrapper. Do you know whats is the case in your application?

2) It seems weird since nothing in the labels code changed. Do you know exactly what the tests were failing. Was the text not in the input? For any chance are you using i18n for the labels content?

3) It seems that it is caused by https://github.com/plataformatec/simple_form/pull/1416. But it should make required fields if you have `required` option explicitly set in the input. Do you have?

4) Are you using i18n for those labels?

> Do you think it will be possible to :
> 
> Add more infos when their is text to add to initializer
We don't do that because application configuration should not need any changes in minor versions, so if it is needed to do something it is a bug.

> When their new default behavior implemented

Default behavior only changes in major versions, and even when that happens it is with deprecation messages.

> Link any changelog entry to the PR when it's possible

The entry is added in the PR itself, so the git blame already give that information.

Thank you again for the report. And let's fix those issues in your application.

**Comment by benoittgt** [comment]
Thanks a lot @rafaelfranca for your answer. I will take the time to answer you properly next days.

**Comment by benoittgt** [comment]
Hello

I found where the issue came from. Our initializer was incomplete. It didn't contains `config.wrappers :default`, and proper content.

It was like : 
```ruby
SimpleForm.setup do |config|
  config.wrappers :horizontal_icon_input, tag: 'div', class: '', error_class: 'field-in-error' do |b|
    b.use :html5
    b.use :placeholder
    b.use :input
    b.use :error, wrap_with: { tag: 'span', class: 'error' }
  end

  config.wrappers :visibility_toggled_password, tag: 'div' do |b|
    b.use :html5
    b.use :input
  end
end
```

I copy past [the last initializer](https://github.com/plataformatec/simple_form/blob/v3.4.0/lib/generators/simple_form/templates/config/initializers/simple_form.rb) and it's ok.

Sorry for my first message, the error was simply related to one file.
