### ISSUE TITLE
simple_fields_for wrapper

### ISSUE THREAD

**Issue by JarLowrey** [plataformatec/simple_form#1508]
Would it be possible to add a wrapper option for these nested fields? More info: https://stackoverflow.com/questions/45722574/specifying-a-wrapper-in-simple-fields-for

Other requests: https://github.com/plataformatec/simple_form/issues/929 https://github.com/plataformatec/simple_form/issues/357 https://github.com/plataformatec/simple_form/issues/1440

**Comment by rafaelfranca** [comment]
As you can see in this  commit it is already posible https://github.com/plataformatec/simple_form/commit/b683b21bf712dd5a2cbc6ea4b5c763b9746bec73

**Comment by JarLowrey** [comment]
Cool, thanks! I cannot seem to figure out how to consume this though. I would like a div with a "nested-fields" class - any ideas?

**Comment by eloyesp** [comment]
Hi, I'm checking this and it doesn't seems to work as I would expect.

I think that the expected wrapper, is a tag around each nested form, so given this:

``` ruby
<%= f.simple_fields_for :addresses, wrapper: 'list-item' do |af| %>
  <%= af.input :street %>
<% end %>
```

I would expect something like:

``` html
<list-item>
  <input name="user[address][1][street]"> <!-- input does use default wrapper -->
  <input type="hidden" value="12" name="user[address][1][id]" <!-- hidden id is wrapped -->
</list-item>
<list-item>
  <input name="user[address][1][street]"> <!-- input does use default wrapper -->
  <input type="hidden" value="12" name="user[address][1][id]" <!-- hidden id is wrapped -->
</list-item>
```

So the problem is that we are using wrapper with two different meanings, the wrapper setting of the form builder (actual behaviour), and item wrapper (tag wrapping nested items on nested forms).

I think the element wrapper cannot be implemented easily by simple form, because most of the implementation is done by rails, but I'm not sure.

Regards.
