### ISSUE TITLE
Remove initializers from Bootstrap and Foundation

### ISSUE THREAD

**Issue by feliperenan** [plataformatec/simple_form#1561]
We don't have plans to support these initializers anymore. We have issues that are not related to Simple Form like bugs related to styles and we must update the initializer on each updates of these Frameworks.

For me, it makes sense to use Bootstrap, Foundation and others as a reference to make Simple Form flexible (see https://github.com/plataformatec/simple_form/pull/1337#issuecomment-350889176), as we are doing with Bootstrap 4, for instance https://github.com/plataformatec/simple_form/pull/1552 and https://github.com/plataformatec/simple_form/pull/1559.

What do you folks think?

**Comment by m5o** [comment]
I think to bundle a well-crafted initializer out of the box would make the most sense. Previously, additional issues and pull requests were basically made on form types/examples that aren't covered by the [bootstrap3 demo app](http://simple-form-bootstrap.herokuapp.com/) in the first place. 

All features and issues related to e.g. bootstrap could be then routed to e.g. [rafaelfranca/simple_form-bootstrap](https://github.com/rafaelfranca/simple_form-bootstrap). Development and organization, issues about this css framework is made here (including tests and working example). 

The then well crafted [`simple_form_bootstrap.rb`](https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/config/initializers/simple_form_bootstrap.rb) can be synced half-yearly/yearly to the [origin's repository](https://github.com/plataformatec/simple_form) build in [generators for `simple_form_bootstrap.rb`](https://github.com/plataformatec/simple_form/blob/master/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb). Since the purpose of a generator is to ship nice defaults and allowance to be easily customizable.

✨ ✌️ ✨

**Comment by rafaelfranca** [comment]
I think that ship is already sailed. Even if we remove the initializer people will still open issues here. I had an idea of extracting the initializer to an umbrella gem that only have the generator template and simple_form as a dependency but it also sucks that we will have to maintain it.

I'm not an user of bootstrap or simple_form anymore and if I was going to make the decision of adding support to bootstrap today, I'd not do at all.

I know bootstrap is one of the reasons people use simple_form, but the fact that the maintainer don't use bootstrap is a problem along with bootstrap releasing breaking changes often.

Back to our decision, I think it make sense to keep the initializer here, make it support bootstrap 4, but explictly say we don't plan to work on any changes to the initializer or support new frameworks. The community would have to maintain them, like @m5o nicely did opening PRs to  rafaelfranca/simple_form-bootstrap.
