### ISSUE TITLE
Rails 5.2.0 upgrade causes "Undefined method `wrapper' for SimpleForm:Module" error

### ISSUE THREAD

**Issue by gregblass** [plataformatec/simple_form#1568]
Just updated to the Rails 5.2.0 release, but I can't start my rails server:

```
/myapp/config/initializers/simple_form.rb:8:in `block in <top (required)>': undefined method `wrappers' for SimpleForm:Module (NoMethodError)
Did you mean?  wrapper_class
	from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/simple_form-1.4.1/lib/simple_form.rb:143:in `setup'
	from /myapp/config/initializers/simple_form.rb:2:in `<top (required)>'
```

**Comment by KeithP** [comment]
@gregblass it is normal for simple_form to have a delayed update after a Rails upgrade. Until #1567 is done, if you go back to this in your gemfile it should work:
 gem 'rails', '~> 5.2.0.beta2'

**Comment by gregblass** [comment]
Sure thing. That is what I did. I'm using RBENV so it was painless to go back. Thanks for the info though.

**Comment by doits** [comment]
When you upgrade to Rails 5.2.0 (non -rc and -beta), it will fetch simple form 1.4.1, since it was the latest version released without rails version restriction (see https://rubygems.org/gems/simple_form/versions/1.4.1). This of course does not work and gives weird errors.

Staying at Rails  5.2 beta or rc (eg. 5.2.0.rc2) allows to install simple form 3.5.1, since it has the restriction `< 5.2`, and `5.2.0.rc2 < 5.2` in semver.

**Comment by feliperenan** [comment]
We released a new version of Simple Form just now. Could you update the gem to the last version and comment on this issue if something goes wrong?

**Comment by KeithP** [comment]
upgrade now works for us thanks @feliperenan
