### ISSUE TITLE
Add association scope configuration option

### ISSUE THREAD

**Issue by Abduvakilov** [plataformatec/simple_form#1611]
I have [discard](https://github.com/jhawthorn/discard) gem on my rails app. The gem requires to change `all` method with `kept`. That's why i have to overwrite collection of `association` with `collection: Model.kept` on every associated input. May we have an option to change `all` with preferred scope?
[The related line](https://github.com/plataformatec/simple_form/blob/3a99d65b082c4422e2f761b1a01e35dee9bd69ae/lib/simple_form/form_builder.rb#L486)

**Comment by feliperenan** [comment]
Hi @Abduvakilov, thanks for the issue :)

I don't think we need this since you have the option to pass it to the `collection` option:

```ruby
f.association :model, collection: Model.kept
```

Simple Form considers that if you don't pass a collection the default will be the `.all` method and I don't think that we should customize this. 

@tegon @rafaelfranca any thoughts?
