### ISSUE TITLE
End up with ..* in the label

### ISSUE THREAD

**Issue by hazemati** [plataformatec/simple_form#1653]
## Precheck

- Do not use the issues tracker for help or support, try Stack Overflow.
- For bugs, do a quick search and make sure the bug has not yet been reported
- Finally, be nice and have fun!

## Environment

- Ruby ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Rails 5.2.3
- Simple Form 4.1.0
## Current behavior

I added my first simple_form and for some reason I'm getting a ..* in front of my labels (email and password). any help would be appreciated
```
  <%= simple_form_for session_path(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <%= f.label :email %>
  <br>
  <%= f.input_field :email %>
  <%= f.error :username, id: 'user_name_error' %>
  <%= f.input :email, label:'Password', required: true, error: 'Password is mandatory, please specify one' %>
  <%= f.button :submit, "Login", id: "LogInButton" %>  
  <% end %>

``` 
![Screenshot from 2019-04-15 08-06-59](https://user-images.githubusercontent.com/14100042/56143513-88978100-5f55-11e9-9b6c-6fa168bda02e.png)

## Expected behavior
The labels should read "email" or "password" not "*..Email" or "*..Password".

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ohboyd** [comment]
I had this issue too, and it would be pretty easy for the simple_form maintainers to change, so it might be worth looking into. At the very least, I'd like to help if someone else runs into the problem using the gem combination I'm using. On a new rails 5.2.3 app, with bootstrap 4.3.1 and simple form 4.1.0,  I had the same issue with an ellipses under the asterisk.

I found a way to solve it, since it actually only happens when using the <abbr> tag. In locales/simple_form.en.yml, if you remove `mark: '*'`, and change `html: '<abbr title="required">*</abbr>'` to `html: '<span title="required">*</span>'`, this removes the ".." that appears under the asterisk. This occurs because there's an included style with bootstrap that adds an underlined dotted border to any abbreviation tags, which allow the user to select that text in order to view the rest of the word. 

The reason I think it seems to make more sense to change this in simple_form is because there's more functionality with the bootstrap feature, and because there isn't a case where we need that functionality with the required asterisk in simple_form. It seems like it's simple enough to just replace <abbr> with <span>. Hopefully this helps, and I'd be happy to submit a quick PR if you'd be interested in the change! :)
