### ISSUE TITLE
4.1 with security fixes?

### ISSUE THREAD

**Issue by envygeeks** [plataformatec/simple_form#1672]
## Environment

- Rails 5.x
- Simple Form 4.1.x
- Ruby 2.5.x

Is it possible to  get a release of 4.1.x  with the security patch in-tow since asking us to jump from 4.1 to 5.0 which generally indicates breaking features for a security fix can cost a lot of resources to have to make happen the same day.  Thanks!

**Comment by tegon** [comment]
Hi,

That's not the case here; we only released a major version because we had to deprecate the `SimpleForm.file_methods` configuration option - which is related to the security issue. Other than that, there are no other breaking changes.

We also didn't release other patches because there's a quick workaround if you can't upgrade: explicit set the input type for your forms that are built based on user input:

```erb
<%= form.input :avatar, as: :file %>
```

You can see the detailed announcement here: http://blog.plataformatec.com.br/2019/09/incorrect-access-control-in-simple-form-cve-2019-16676/
